language: java
jdk: openjdk11

services:
  - docker

env:
  global:
    - SONATYPE_DIR=$HOME/.sonatype
    - SONATYPE_STAGING_FILE=${SONATYPE_DIR}/staging-repository.txt
    - MAVEN_PUSH=true
    - GIT_PUSH=true
    - IGNORE_TAG_CHECKOUT_FAILURE=false
    - DEPLOY_EXISTING=true
    - ACTIVITI_CORE_VERSION=7.1.197
    - ACTIVITI_CLOUD_DEPENDENCIES_VERSION=7.1.345
    - CHECK_VERSIONS=
    - SRC_DIR=${TRAVIS_BUILD_DIR}/..
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - echo BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}
  - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY"
  - mkdir -p $HOME/.m2
  - cp settings.xml $HOME/.m2
  - mkdir -p $SONATYPE_DIR

cache:
  directories:
    - ~/.m2/repository
    - ~/.sonatype

jobs:
  include:
    - stage: create tag
      if: (commit_message =~ /\[Release\] .+/) AND (tag IS blank)
      script: ./create-tag.sh

    - stage: Create Maven Central stating repository
      if: tag =~ /v7\..+/
      script: ./create-staging-repository.sh

    - stage: Release Activi Core
      if: tag =~ /v7\..+/
      env:
        - PROJECTS=Activiti
      script: ./release-ci.sh

    - stage: Release Activi Cloud
      if: tag =~ /v7\..+/
      env:
        - PROJECTS=activiti-cloud
      script: ./release-ci.sh

    - stage: Release Activiti Cloud Examples
      if: tag =~ /v7\..+/
      env:
        - MAVEN_PUSH=
        - PROJECTS=activiti-cloud-examples
      script: ./release-ci.sh

    - stage: Release Activi Cloud Dependencies
      if: tag =~ /v7\..+/
      env:
        - PROJECTS=activiti-cloud-bom
      script: ./release-ci.sh

    - stage: Release Docker Images
      if: tag =~ /v7\..+/
      env:
        - MAVEN_PUSH=
        - DOCKER_PUSH=true
      name: "Docker - Activiti Cloud Examples"
      script: PROJECTS=activiti-cloud-examples ./dockerpush-all.sh

    - name: "Docker - Activiti Modeling App"
      if: tag =~ /v7\..+/
      script: PROJECTS=activiti-cloud-modeling-app ./dockerpush-all.sh
