if: ${TRAVIS_EVENT_TYPE} == "api"
language: java
jdk: openjdk11
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - echo BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}
  - mkdir -p $HOME/.m2
  - cp settings.xml $HOME/.m2
script:
#  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" == "master" ]]; then mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease; fi
  - bash release-ci.sh
cache:
  directories:
    - ~/.m2/repository
