language: java
jdk: openjdk11

services:
  - docker

env:
  global:
    - SONATYPE_STAGING_FILE=staging-repository.txt
    - MAVEN_PUSH=true
    - GIT_PUSH=true
    - IGNORE_TAG_CHECKOUT_FAILURE=false
    - DEPLOY_EXISTING=true
    - ACTIVITI_CLOUD_DEPENDENCIES_VERSION=7.1.351
    - CHECK_VERSIONS=
    - SRC_DIR=${TRAVIS_BUILD_DIR}/..
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - echo BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}
  - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY"
  - mkdir -p ${HOME}/.m2
  - cp settings.xml $HOME/.m2

cache:
  directories:
    - ${HOME}/.m2/repository

jobs:
  include:
    - stage: Create tag
      if: (commit_message =~ /\[Release\] .+/) AND (tag IS blank)
      script: ./create-tag.sh

    - stage: Release Activiti Core
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti
      script: ./release-ci.sh

    - stage: Release Activiti Cloud
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti-cloud
      script: ./release-ci.sh

    - stage: Release Activiti Cloud Examples
      if: tag =~ /7\..+/
      env:
        - MAVEN_PUSH=
        - PROJECTS=activiti-cloud-examples
      script: ./release-ci.sh

    - stage: Release Activiti Cloud Dependencies
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti-cloud-bom
      # first build examples that are not published to central, then release BOM
      script: MAVEN_PUSH= PROJECTS=activiti-cloud-examples ./release-ci.sh && ./release-ci.sh

    - stage: Release Docker Images
      if: tag =~ /7\..+/
      env:
        - MAVEN_PUSH=
        - DOCKER_PUSH=true
      name: "Activiti Cloud Examples"
      script: PROJECTS=activiti-cloud-examples ./release-docker.sh

    - name: "Activiti Modeling App"
      if: tag =~ /7\..+/
      script: PROJECTS=activiti-cloud-modeling-app ./release-docker.sh
