language: java
jdk: openjdk11
node_js:
  - "12.13.1"

services:
  - docker

env:
  global:
    - NEXUS_STAGING_FILE=maven-config/staging-repository.txt
    - SETTINGS_XML_FILE_PATH=maven-config/settings.xml
    - MAVEN_PUSH=true
    - GIT_PUSH=true
    - IGNORE_TAG_CHECKOUT_FAILURE=false
    - DEPLOY_EXISTING=true
    - CHECK_VERSIONS=
    - SRC_DIR=${TRAVIS_BUILD_DIR}/..
    - NODE_OPTIONS=--max_old_space_size=30000
    - HELM_VERSION=2.12.3
    - KUBERNETES_VERSION=1.14.8
    - TRAVIS_WAIT_TIMEOUT=${TRAVIS_WAIT_TIMEOUT:-180}
    - GITHUB_CHARTS_REPO="https://github.com/Activiti/activiti-cloud-helm-charts.git"
    - GITHUB_HELM_REPO_URL="https://activiti.github.io/activiti-cloud-helm-charts/"

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - echo BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}
  - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY"
  - mkdir -p ${HOME}/.m2
  - cp ${SETTINGS_XML_FILE_PATH} $HOME/.m2

  - export PREVIEW_NAMESPACE=$(echo "v$TRAVIS_BRANCH-$TRAVIS_BUILD_ID"|  tr '[:upper:]' '[:lower:]'|tr . -)
  - ORG='activiti'
  - export HELM_RELEASE_NAME="$TRAVIS_BRANCH-$TRAVIS_BUILD_ID"
  - export GATEWAY_HOST="gateway.$PREVIEW_NAMESPACE.$GLOBAL_GATEWAY_DOMAIN"
  - export SSO_HOST="identity.$PREVIEW_NAMESPACE.$GLOBAL_GATEWAY_DOMAIN"
  - curl -Ls -o updatebot.jar   https://repo1.maven.org/maven2/io/jenkins/updatebot/updatebot/1.1.53/updatebot-1.1.53.jar
  - sudo cp updatebot.jar  /usr/bin/updatebot.jar
  - echo "java -jar /usr/bin/updatebot.jar \$@" > updatebot
  - sudo cp updatebot  /usr/bin/updatebot
  - sudo chmod a+x /usr/bin/updatebot
  - echo -e "https://$GITHUB_USER:$GITHUB_TOKEN@github.com" >>  ~/.git-credentials
  - curl -s https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar zx
  - sudo mv linux-amd64/helm /usr/local/bin/
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
  - chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - kubectl config set-cluster default-cluster --server=${K8S_API_URL}
  - kubectl config set-credentials default-admin --token=${K8S_API_TOKEN}
  - kubectl config set-context default-system --cluster=default-cluster --user=default-admin
  - kubectl config use-context default-system
  - kubectl get ns|| return 1

jobs:
  include:
    - stage: Create tag
      if: (commit_message =~ /\[Release\] .+/ OR type = cron) AND (tag IS blank)
      script: ./create-tag.sh

    - stage: Release Activiti Core
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti
      script: ./release-ci.sh

    - stage: Release Activiti Cloud
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti-cloud
      script: ./release-ci.sh

    - stage: Release Activiti Cloud Modeling App
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti-modeling-app
      script: ./release-ci.sh

    - stage: Release Activiti Cloud Application
      if: tag =~ /7\..+/
      env:
        - PROJECTS=activiti-cloud-application
      script: ./release-ci.sh

    - stage: Release Docker Images
      if: tag =~ /7\..+/
      env:
        - DOCKER_PUSH=true
      name: "Activiti Cloud Example Images"
      script: ./release-docker-activiti-cloud-example-images.sh

    - name: "Activiti Modeling App"
      if: tag =~ /7\..+/
      env:
        - DOCKER_PUSH=true
      script: ./release-docker-modeling-app.sh

    - stage: Release Helm Chart
      if: tag =~ /7\..+/
      script:
        - pwd
        - export VERSION=$(cat VERSION)
        - export HELM_ACTIVITI_VERSION=$(cat VERSION)
        - ./release-helm.sh
    - stage: Remove Helm Chart
      if: tag =~ /7\..+/
      script:
        - cd activiti-cloud-application/activiti-cloud-dependencies && make delete|| echo "Trying to delete helm chart" &&  cd -
        - kubectl delete ns ${PREVIEW_NAMESPACE} || echo "Trying to delete namespace"


after_failure:
  - cd activiti-cloud-application/activiti-cloud-dependencies && make delete|| echo "Trying to delete helm chart" &&  cd -
  - kubectl delete ns ${PREVIEW_NAMESPACE} || echo "Trying to delete namespace"

