name: Mock release cleanup
description: Remove mock release and tag on a repository
inputs:
  version:
    description: Mock release version to be removed from tags and releases (should end with -mock)
    required: true
  repo:
    description: Path the repository
    required: true
  gh-token:
    description: 'GitHub Token'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.gh-token }}

    - uses: Alfresco/alfresco-build-tools/.github/actions/git-check-existing-tag@34b2301fc6245fa98ed73a82e04d4f9ab4eb5a3f #v3.6.0
      id: check-tag
      with:
        tag: ${{ inputs.version }}

    - name: Delete tag if it exist and ends with "-mock"
      if: steps.check-tag.outputs.exists == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
        VERSION: ${{ inputs.version }}
      run: |
        if [[ "${VERSION}" == *-mock ]]; then
          echo "Removing '${VERSION}' tag from: ${REPO}"
          git push origin --delete ${VERSION} || true
        else
          echo "Error: The provided version does not end with '-mock.'"
          exit 1
        fi

    - name: Delete release if the provided version ends with "-mock"
      id: delete_version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
        VERSION: ${{ inputs.version }}
        REPO: ${{ inputs.repo }}
      run: |
        if [[ "${VERSION}" == *-mock ]]; then
          echo "Removing '${VERSION}' release from: ${REPO}"
          gh release delete -R ${REPO} -y ${VERSION}
        else
          echo "Error: The provided version does not end with '-mock.'"
          exit 1
        fi
