name: Mock release cleanup
description: Removal of release and tag
inputs:
  version:
    description: 'Mock release version to be removed from tags and releases'
    required: true
  repo:
    description: 'Path to repo'
    required: true
  gh-token:
    description: 'gh token'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.token }}

    - uses: Alfresco/alfresco-build-tools/.github/actions/git-check-existing-tag@v3.6.0
      id: check-tag
      with:
        tag: ${{ inputs.version }}


    - name: Delete release if the provided version ends with "-mock"
      id: delete_version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        VERSION: ${{ inputs.version }}
        REPO: ${{ inputs.repo }}
      run: |
        if [[ "${VERSION}" == *-mock ]]; then
          echo "Removing release from: ${REPO}"
          gh release delete -R ${REPO} -y ${VERSION} || true
        else
          echo "version does not end with '-mock'."
          echo "Error: The provided version does not end with '-mock.'"
          exit 1
        fi

    - name: Delete tag if it exist
      if: steps.check-tag.outputs.exists == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        VERSION: ${{ inputs.version }}
      run: |
        echo "Removing tag from: ${REPO}"
        git push origin --delete ${VERSION} || true
