name: Update base tags for Java projects
description: Update base tags for Java projects
inputs:
  tag-pattern:
    description: The pattern to be used to filter the existing tags
    required: true
outputs:
  activiti-tag:
    description: The base tag of Activiti project used for this release
    value: ${{ steps.java-tags.outputs.activiti-tag }}
  activiti-cloud-tag:
    description: The base tag of Activiti Cloud project used for this release
    value: ${{ steps.java-tags.outputs.activiti-cloud-tag }}
  activiti-cloud-application-tag:
    description: The base tag of Activiti Cloud Application project used for this release
    value: ${{ steps.java-tags.outputs.activiti-cloud-application-tag }}
runs:
  using: composite
  steps:
    - name: Fetch Java Project Tags to release
      id: java-tags
      shell: bash
      env:
        TAG_PATTERN: ${{ inputs.tag-pattern }}
      run: |
        ./gh-actions-scripts/fetch-activiti-tags-from.sh -t "$TAG_PATTERN" -p repos/activiti-cloud-application

    - uses: ./.github/actions/update-activiti-base-tag
      with:
        tag: ${{ steps.java-tags.outputs.activiti-tag }}

    - uses: ./.github/actions/update-activiti-cloud-base-tag
      with:
        tag: ${{ steps.java-tags.outputs.activiti-cloud-tag }}

    - uses: ./.github/actions/update-activiti-cloud-application-base-tag
      with:
        tag: ${{ steps.java-tags.outputs.activiti-cloud-application-tag }}
