name: Release Activiti Cloud

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches: [ gh-3903-gh-action-workflow ]
  pull_request:
    branches: [ gh-3903-gh-action-workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pre-commit:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@master

  prepare-release:
    runs-on: ubuntu-20.04
    # needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - name: fetch-tags-to-release
        run: |
          ./gh-actions-scripts/fetch-versions.sh

  release-docker-images:
    runs-on: ubuntu-20.04
    needs: prepare-release
    steps:
      - uses: actions/checkout@v3
      - name: tag-docker-images
        run: |
          ./gh-actions-scripts/dummy-step.sh
      - name: update-helm-charts
        run: |
          ./gh-actions-scripts/dummy-step.sh
      - name: push-helm-charts
        run: |
          ./gh-actions-scripts/dummy-step.sh

  create-artifacts-staging-env:
    runs-on: ubuntu-20.04
    needs: prepare-release
    steps:
      - uses: actions/checkout@v3
      - name: create-staging-environment
        run: |
          ./gh-actions-scripts/dummy-step.sh

  release-maven-artifacts:
    runs-on: ubuntu-20.04
    needs: create-artifacts-staging-env
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        repo: ['Activiti','activiti-cloud','activiti-cloud-application']
    steps:
      - name: Checkout activiti-script
        uses: actions/checkout@v3
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: 'Activiti/${{ matrix.repo }}'
          path: 'repo/${{ matrix.repo }}'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: update-and-tag-pom-versions
        run: |
          mvn -version
      - name: maven-build
        run: |
          ./gh-actions-scripts/mvn-build.sh "repo/${{ matrix.repo }}"
      - name: upload-artifacts
        run: |
          ./gh-actions-scripts/dummy-step.sh ${{ matrix.repo }}

  release-artifacts-staging-env:
    runs-on: ubuntu-20.04
    needs: release-maven-artifacts
    steps:
      - uses: actions/checkout@v3
      - name: create-staging-environment
        run: |
          ./gh-actions-scripts/dummy-step.sh
