name: Release Activiti Cloud

# TODO we should run the pre-commit tasks only in the case of
# TODO a PR modifying this repo (activiti-scripts) and not
# TODO when launching a release process

# TODO we should run the release process only when a certain
# TODO commit message is matched [ci:release]

# TODO we should support the rollback of a release if possible
# TODO with a commit message [ci:rollback]

# TODO we need to change the branches we use to perform the release
# TODO we could delete master and use develop.

# TODO after the release process succeeds we need to update the
# TODO release.yaml file with the versions of Activiti, activiti-cloud,
# TODO activiti-cloud-application used to create the release
on:
  push:
    branches: [ gh-3903-gh-action-workflow ]
  pull_request:
    branches: [ gh-3903-gh-action-workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NEXUS_URL: "https://artifacts.alfresco.com/nexus"
  NEXUS_PROFILE_ID: "${{ secrets.NEXUS_ACTIVITI7_PROFILE_ID }}"
  NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
  NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
  NEXUS_STAGING_PROFILE_PATTERN: "activiti-7-community-staging-profile-[0-9]*"
  MAVEN_CONFIG_DIR: "maven-config"

jobs:

  prepare-release:
    runs-on: ubuntu-20.04
    outputs:
      activiti-cloud-application: ${{ steps.tags.outputs.activiti-cloud-application }}
      activiti-cloud: ${{ steps.tags.outputs.activiti-cloud }}
      activiti: ${{ steps.tags.outputs.activiti }}
      BRANCH: ${{ steps.tags.outputs.BRANCH }}
      VERSION: ${{ steps.tags.outputs.VERSION }}
      NEXT_VERSION: ${{ steps.tags.outputs.NEXT_VERSION }}
      MOCK: ${{ steps.tags.outputs.MOCK }}

    steps:
      # - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@@v1.4.0
      - name: Installing activiti-scripts
        uses: actions/checkout@v3

      - name: Checkout activiti-cloud-application
        uses: actions/checkout@v3
        with:
          repository: 'Activiti/activiti-cloud-application'
          path: 'repos/activiti-cloud-application'

      - name: fetch-tags-to-release
        id: tags
        run: |
          VERSION=$(yq e '.release.version' release.yaml)
          BRANCH=$(yq e '.release.version' release.yaml)
          NEXT_VERSION=$(yq e '.release.nextVersion' release.yaml)
          MOCK=$(yq e '.release.mock' release.yaml)

          ./gh-actions-scripts/fetch-activiti-tags-from.sh -t "${VERSION%-mock*}-alpha*" -p repos/activiti-cloud-application

          if [ "$MOCK" == "true" ]; then
            VERSION=$VERSION-mock
          fi

          echo "::set-output name=BRANCH::$BRANCH"
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=NEXT_VERSION::$NEXT_VERSION"
          echo "::set-output name=MOCK::$MOCK"

  release-docker-images:
    runs-on: ubuntu-20.04
    needs: prepare-release
    env:
      DOCKER_IMAGES: "example-runtime-bundle,activiti-cloud-query,example-cloud-connector,activiti-cloud-modeling"
      BASE_TAG: "${{ needs.prepare-release.outputs.activiti-cloud-application }}"
      RELEASE_VERSION: "${{ needs.prepare-release.outputs.VERSION }}"
      DOCKERHUB_ORG: activiti
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_ACCESS_TOKEN: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      MOCK: "${{ needs.prepare-release.outputs.MOCK }}"
    steps:
      - name: Checkout activiti-scripts
        uses: actions/checkout@v3

      - name: tag-docker-images
        working-directory: ./gh-actions-scripts
        run: |
          for DOCKER_IMAGE in ${DOCKER_IMAGES//,/ }
          do
            echo "releasing $DOCKER_IMAGE from base tag $BASE_TAG with tag $RELEASE_VERSION"
            ./tag-docker-image.sh \
              $BASE_TAG \
              $RELEASE_VERSION \
              $DOCKERHUB_ORG \
              $DOCKER_IMAGE \
              $DOCKERHUB_USERNAME \
              $DOCKERHUB_ACCESS_TOKEN
            echo "$DOCKER_IMAGE released."
          done
      - name: update-helm-charts
        env:
          VERSION: $(cat VERSION)
          RELEASE_VERSION: ${{ needs.prepare-release.outputs.VERSION }}
          HELM_ACTIVITI_VERSION: $(cat VERSION)
          SSO_PROTOCOL: https
          GATEWAY_PROTOCOL: https

        run: |
          # TODO the release-helm scripts deploys an activiti cloud application
          # TODO launches acceptance tests. Is this necessary?
          set -e
          #./release-helm.sh
          #
          # helm delete --no-hooks ${PREVIEW_NAME} --namespace ${PREVIEW_NAME} || echo "Trying to delete chart"
          # kubectl delete ns ${PREVIEW_NAME} || echo "Trying to delete namespace"
          #
      - name: push-helm-charts
        run: |
          ./gh-actions-scripts/dummy-step.sh

  create-artifacts-staging-repo:
    runs-on: ubuntu-latest
    needs: prepare-release
    outputs:
      STAGING_REPOSITORY: ${{ steps.staging.outputs.STAGING_REPOSITORY }}
    env:
      RELEASE_VERSION: ${{ needs.prepare-release.outputs.VERSION }}
      MOCK: ${{ needs.prepare-release.outputs.MOCK }}
    steps:
      - uses: actions/checkout@v3
      - name: create-staging-repository
        id: staging
        working-directory: ${{ env.MAVEN_CONFIG_DIR }}
        run: |
          cp staging-repository-template.xml staging-repository-template.xml.bak
          sed "s/RELEASE_VERSION/${RELEASE_VERSION}/g" staging-repository-template.xml.bak > staging-repository-template.xml

          NEXUS_STAGING_DATA=$(curl -d @staging-repository-template.xml \
            -u "${NEXUS_USERNAME}":"${NEXUS_PASSWORD}" \
            -H "Content-Type:application/xml" \
            "${NEXUS_URL}"/service/local/staging/profiles/"${NEXUS_PROFILE_ID}"/start | \
            grep stagedRepositoryId | grep -o "$NEXUS_STAGING_PROFILE_PATTERN")

          echo "Stating repository $NEXUS_STAGING_DATA"

          cp settings.xml settings.xml.bak
          sed "s/STAGING_ID/${NEXUS_STAGING_DATA}/g" "settings.xml.bak" > settings.xml

          echo "::set-output name=STAGING_REPOSITORY::$NEXUS_STAGING_DATA"

      - uses: actions/upload-artifact@v3
        with:
          name: maven-settings-xml
          path: ${{ github.workspace }}/${{ env.MAVEN_CONFIG_DIR }}/settings.xml
          if-no-files-found: error

  release-activiti:
    runs-on: ubuntu-latest
    needs: ["prepare-release","create-artifacts-staging-repo"]
    steps:
      - name: Checkout activiti-scripts
        uses: actions/checkout@v3

      - uses: ./.github/actions/release-maven
        with:
          repo: Activiti
          base-tag: ${{  needs.prepare-release.outputs.activiti }}
          release-version: ${{ needs.prepare-release.outputs.VERSION }}
          staging-repository-id: ${{ needs.create-artifacts-staging-repo.outputs.STAGING_REPOSITORY }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          gpg-passphrase: "${{ secrets.GPG_PASSPHRASE }}"
          gpg-secret-keys: "${{ secrets.GPG_SECRET_KEYS }}"
          gpg-owner-trust: "${{ secrets.GPG_OWNERTRUST }}"
          nexus-username: "${{ secrets.NEXUS_USERNAME }}"
          nexus-password: "${{ secrets.NEXUS_PASSWORD }}"

  release-activiti-cloud:
    runs-on: ubuntu-latest
    needs: ["prepare-release","create-artifacts-staging-repo", "release-activiti"]
    steps:
      - name: Checkout activiti-scripts
        uses: actions/checkout@v3

      - uses: ./.github/actions/release-maven
        with:
          repo: activiti-cloud
          base-tag: ${{  needs.prepare-release.outputs.activiti-cloud }}
          release-version: ${{ needs.prepare-release.outputs.VERSION }}
          staging-repository-id: ${{ needs.create-artifacts-staging-repo.outputs.STAGING_REPOSITORY }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          gpg-passphrase: "${{ secrets.GPG_PASSPHRASE }}"
          gpg-secret-keys: "${{ secrets.GPG_SECRET_KEYS }}"
          gpg-owner-trust: "${{ secrets.GPG_OWNERTRUST }}"
          nexus-username: "${{ secrets.NEXUS_USERNAME }}"
          nexus-password: "${{ secrets.NEXUS_PASSWORD }}"

  release-activiti-cloud-application:
    runs-on: ubuntu-latest
    needs: ["prepare-release","create-artifacts-staging-repo", "release-activiti-cloud"]
    steps:
      - name: Checkout activiti-scripts
        uses: actions/checkout@v3

      - uses: ./.github/actions/release-maven
        with:
          repo: activiti-cloud-application
          base-tag: ${{  needs.prepare-release.outputs.activiti-cloud-application }}
          release-version: ${{ needs.prepare-release.outputs.VERSION }}
          staging-repository-id: ${{ needs.create-artifacts-staging-repo.outputs.STAGING_REPOSITORY }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          gpg-passphrase: "${{ secrets.GPG_PASSPHRASE }}"
          gpg-secret-keys: "${{ secrets.GPG_SECRET_KEYS }}"
          gpg-owner-trust: "${{ secrets.GPG_OWNERTRUST }}"
          nexus-username: "${{ secrets.NEXUS_USERNAME }}"
          nexus-password: "${{ secrets.NEXUS_PASSWORD }}"

  release-artifacts-staging-env:
    runs-on: ubuntu-20.04
    needs: release-activiti-cloud-application
    steps:
      - uses: actions/checkout@v3
      - name: close-and-release-staging-environment
        run: |
          # TODO Should we close and release the nexus artifact staging env?
          ./gh-actions-scripts/dummy-step.sh

  # TODO should this step be skipped for the mock release?
  finalize-branch:
    runs-on: ubuntu-20.04
    needs: ["prepare-release","release-activiti-cloud-application"]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        # TODO Should we add also activiti-cloud-modeling?
        repo: ['Activiti','activiti-cloud','activiti-cloud-application']
    env:
      NEXT_VERSION: "${{ needs.prepare-release.outputs.NEXT_VERSION }}"
    steps:
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: 'Activiti/${{ matrix.repo }}'
          path: 'repos/${{ matrix.repo }}'
          ref: '${{ needs.prepare-release.outputs.BRANCH }}'

      - name: update-to-next-version
        working-directory: repos/${{ matrix.repo }}
        run: |
          # TODO Check that the update is updating all the needed dependencies
          # TODO e.g.: activiti-cloud 7.3.1-SNAPSHOT should refer to Activiti 7.3.1-SNAPSHOT
          mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false

      - name: commit-and-push
        working-directory: repos/${{ matrix.repo }}
        run: |
          # TODO which user should commit and push?
          echo "commit and push repository"
          cat pom.xml
