name: Mock release cleanup

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mock release to be removed from tags and releases'
        required: true

jobs:
  delete_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/remove-mock-release-and-tag
        with:
          version: ${{ inputs.version }}
          repo: Activiti/activiti-cloud-full-chart
          gh-token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: actions/checkout@v3
