name: Mock release cleanup

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mock release to be removed from tags and releases'
        required: true

jobs:
  delete_version:
    runs-on: ubuntu-latest
    steps:
      - name: Delete version if the provided version ends with "-mock"
        id: delete_version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          REPO: ${{ inputs.repository }}
          VERSION: ${{ inputs.version }}
        run: |
          if [[ "${VERSION}" == *-mock ]]; then
            gh release delete -R Activiti/activiti-cloud-full-chart -y --cleanup-tag ${VERSION}
            echo "Activiti/activiti-cloud-full-chart cleaned"
            gh release delete -R Activiti/activiti-scripts -y --cleanup-tag ${VERSION}
            echo "Activiti/activiti-scripts cleaned"
            gh release delete -R Activiti/activiti-cloud -y --cleanup-tag ${VERSION}
            echo "Activiti/activiti-cloud cleaned"
            gh release delete -R Activiti/activiti-cloud-common-chart -y --cleanup-tag ${VERSION}
            echo "Activiti/activiti-cloud-common-chart cleaned"
            gh release delete -R Activiti/Activiti -y --cleanup-tag ${VERSION}
            echo "Activiti/activiti cleaned"

          else
            echo "version does not end with '-mock'."
            echo "Error: The provided version does not end with '-mock.'"
            exit 1
          fi
