name: Mock release cleanup

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mock release to be removed from tags and releases'
        required: true

jobs:
  delete_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { name: "Activiti/activiti-cloud-full-chart", type: "release" }
          - { name: "Activiti/activiti-cloud", type: "release" }
          - { name: "Activiti/activiti-cloud-common-chart", type: "release" }
          - { name: "Activiti/Activiti", type: "release" }
          - { name: "Activiti/activiti-scripts", type: "tag" }
      fail-fast: false
    steps:
      - name: Delete version if the provided version ends with "-mock"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}
        run: |
          if [[ "${VERSION}" != *-mock ]]; then
            echo "Error: The provided version does not end with '-mock.'"
            exit 1
          fi
          
          echo "Starting cleanup for version: ${VERSION} from ${{ matrix.repo.name }}"
          
          if [[ "${{ matrix.repo.type }}" == "release" ]]; then
            if gh release delete -R ${{ matrix.repo.name }} -y --cleanup-tag ${VERSION}; then
              echo "✓ Deleted release from ${{ matrix.repo.name }}"
            else
              echo "❌ Failed to delete release from ${{ matrix.repo.name }}"
              exit 1
            fi
          else
            if gh api --silent -X DELETE /repos/${{ matrix.repo.name }}/git/refs/tags/${VERSION}; then
              echo "✓ Deleted tag from ${{ matrix.repo.name }}"
            else
              echo "❌ Failed to delete tag from ${{ matrix.repo.name }}"
              exit 1
            fi
          fi
