name: Mock release cleanup

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mock release to be removed from tags and releases'
        required: true

jobs:
  delete_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [ 'Activiti/activiti-cloud-full-chart',
                      'Activiti/activiti-scripts',
                      'Activiti/activiti-cloud',
                      'Activiti/activiti-cloud-common-chart',
                      'Activiti/activiti' ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - uses: ./.github/actions/remove-mock-release-and-tag
        with:
          version: ${{ inputs.version }}
          repo: ${{ matrix.repository }}
          gh-token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
