name: Run pre-checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@7c33225b191ec9de4fa385b9a88c895211f04784 # v8.35.2
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: hyland/github-actions-ensure-sha-pinned-actions@cda680a0136c8c0daede32a0da794dd0578ea661 # v1.0.0
