name: Run pre-checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@b7013d54c5255a71f931fd1316d0fcdb5c36c13c # v15.9.1
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: hyland/github-actions-ensure-sha-pinned-actions@1afac08cba4e5ea12263a46f49683570690ae3af # v1.2.0
