name: release Maven artifacts
on:
  workflow_call:
    inputs:
      repo:
        description: "Repository to be released"
        type: string
        required: true
      base-tag:
        description: "The name of the tag from where the release will be created"
        type: string
        required: true
      release-version:
        description: "The name of the version to be released"
        type: string
        required: true
      staging-repository-id:
        description: "The id of the staging repository where the release artifacts will be stored"
        type: string
        required: true
    secrets:
      github-token:
        description: "The token to used to clone the repositories"
        required: true
      git-username:
        description: "The username for git commit"
        required: true
      gpg-passphrase:
        description: "GPG passphrase"
        required: true
      gpg-secret-keys:
        description: "GPG secrets key"
        required: true
      gpg-owner-trust:
        description: "GPG Owner trust"
        required: true
      nexus-username:
        description: "Nexus user name"
        required: true
      nexus-password:
        description: "Nexus password"
        required: true

env:
  GPG_EXECUTABLE: "gpg"
  GPG_PASSPHRASE: "${{ secrets.gpg-passphrase }}"
  GPG_SECRET_KEYS: "${{ secrets.gpg-secret-keys }}"
  GPG_OWNERTRUST: "${{ secrets.gpg-owner-trust }}"
  NEXUS_USERNAME: "${{ secrets.nexus-username }}"
  NEXUS_PASSWORD: "${{ secrets.nexus-password }}"
  NEXUS_URL: "https://artifacts.alfresco.com/nexus"
  RELEASE_VERSION: ${{ inputs.release-version }}
  BASE_TAG: ${{ inputs.base-tag }}
  STAGING_REPOSITORY_ID: ${{ inputs.staging-repository-id }}
  REPO_DIR: repos/${{ inputs.repo }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout activiti-scripts
        uses: actions/checkout@v3

      - name: Checkout ${{ inputs.repo }}
        uses: actions/checkout@v3
        with:
          repository: 'Activiti/${{ inputs.repo }}'
          ref: ${{ inputs.base-tag }}
          path: '${{ env.REPO_DIR }}'
          token: ${{ secrets.github-token }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Set up M2_DIR
        run: echo "M2_DIR=$HOME/.m2" >> $GITHUB_ENV

      - name: Download setting.xml
        uses: actions/download-artifact@v3
        with:
          name: maven-settings-xml
          path: ${{ env.M2_DIR }}

      - name: Display M2 configuration
        run: |
          echo ".m2 dir: $(pwd)"
          cat settings.xml
        working-directory: ${{ env.M2_DIR }}

      - name: Configure GPG
        run: |
          gpg --version
          echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | $GPG_EXECUTABLE --import-ownertrust  --no-tty --batch --yes

      - name: update-pom-to-release-version
        working-directory: ${{ env.REPO_DIR }}
        run: |
          # TODO Check that the update is updating all the needed dependencies
          # TODO e.g.: activiti-cloud 7.3.1 should refer to Activiti 7.3.1
          ../../gh-actions-scripts/update-pom-version.sh "$RELEASE_VERSION" "$BASE_TAG"

      - name: maven-build-and-upload
        working-directory: ${{ env.REPO_DIR }}
        run: |
          echo "Deploying to repository $STAGING_REPOSITORY_ID"
          mvn clean deploy \
            -DperformRelease \
            -DskipTests \
            -Dmaven.compiler.release=11 \
            -Dmaven.artifact.threads=30 \
            -B \
            -DaltReleaseDeploymentRepository=nexus-releases-staging-fixed::default::"${NEXUS_URL}"/service/local/staging/deployByRepositoryId/"$STAGING_REPOSITORY_ID " \
            -Dhttp.keepAlive=false \
            -Dmaven.wagon.http.pool=false \
            -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
            -T 2C

      - name: Commit changes
        uses: Alfresco/alfresco-build-tools/.github/actions/git-commit-changes@v1.9.0
        with:
          username: ${{ secrets.git-username }}
          add-options: -u
          commit-message: "Release version ${{ inputs.release-version}}"
          repository-directory: ${{ env.REPO_DIR }}

      - name: create tag
        working-directory: ${{ env.REPO_DIR }}
        run: |
          git tag -f -a "${RELEASE_VERSION}" -m "Release version ${RELEASE_VERSION}"
          git push origin "${RELEASE_VERSION}"
