name: Release Activiti Cloud

on:
  push:
    branches: ['releases/main/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  load-release-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.load-descriptor.outputs.version }}
      next-version: ${{ steps.load-descriptor.outputs.next-version }}
      mock: ${{ steps.load-descriptor.outputs.mock }}
      activiti-tag: ${{ steps.load-descriptor.outputs.activiti-tag }}
      activiti-cloud-tag: ${{ steps.load-descriptor.outputs.activiti-cloud-tag }}
      activiti-cloud-application-tag: ${{ steps.load-descriptor.outputs.activiti-cloud-application-tag }}
      common-chart-tag: ${{ steps.load-descriptor.outputs.common-chart-tag }}
      full-chart-tag: ${{ steps.load-descriptor.outputs.full-chart-tag }}
      staging-repository: ${{ steps.load-descriptor.outputs.staging-repository }}

    steps:
      - name: Installing activiti-scripts
        uses: actions/checkout@v3

      - uses: Alfresco/alfresco-build-tools/.github/actions/load-release-descriptor@v1.23.0
        id: load-descriptor
        with:
          release-descriptor: release.yaml

  release-activiti:
    runs-on: ubuntu-latest
    needs: [load-release-info]
    outputs:
      staging-repository: ${{ steps.staging.outputs.staging-repository }}
    steps:
      - name: create-staging-repository
        id: staging
        uses: Alfresco/alfresco-build-tools/.github/actions/nexus-create-staging@v1.27.0
        with:
          staging-description: Activiti staging ${{ needs.load-release-info.outputs.version }}
          nexus-profile-id: ${{ secrets.NEXUS_ACTIVITI7_PROFILE_ID }}
          nexus-username: ${{ secrets.NEXUS_USERNAME }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Checkout activiti-scripts
        uses: actions/checkout@v3

      - uses: Alfresco/alfresco-build-tools/.github/actions/maven-release@v1.27.0
        with:
          repo: Activiti/Activiti
          base-ref: ${{  needs.load-release-info.outputs.activiti-tag }}
          release-version: ${{ needs.load-release-info.outputs.version }}
          staging-repository: ${{ steps.staging.outputs.staging-repository }}
          git-username: ${{ secrets.BOT_GITHUB_USERNAME }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          gpg-passphrase: "${{ secrets.GPG_PASSPHRASE }}"
          gpg-secret-keys: "${{ secrets.GPG_SECRET_KEYS }}"
          gpg-owner-trust: "${{ secrets.GPG_OWNERTRUST }}"
          nexus-username: "${{ secrets.NEXUS_USERNAME }}"
          nexus-password: "${{ secrets.NEXUS_PASSWORD }}"

  create-scripts-tag:
    runs-on: ubuntu-latest
    needs: [ release-activiti ]
    env:
      RELEASE_VERSION: ${{ needs.load-release-info.outputs.version }}
      STAGING_REPOSITORY_FILE: maven-config/staging-repository.txt
      GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}

    steps:
      - name: Checkout activiti-scripts
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/git-check-existing-tag@v1.23.0
        id: check-tag
        with:
          tag: ${{ env.RELEASE_VERSION }}

      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email ${GIT_USERNAME}@users.noreply.github.com
          git tag "$RELEASE_VERSION" -m "Release version $RELEASE_VERSION"
          git push origin "$RELEASE_VERSION"
